"""Find held frames in hand-drawn animation and plan how to rebuild it.

Animation is drawn "on 2s" or "on 3s": the artist draws 12 pictures a second
and each is photographed twice or three times to fill 24fps. Playing that back
looks stepped, and interpolating it directly does nothing useful, because most
neighbouring frames are byte-identical -- there is no motion to interpolate.

So the pipeline first has to recover the real drawings:

    source     A A B B C C C D D          9 frames, drawn on 2s
    drawings   A   B   C     D            4 unique drawings
    plan       A   B   C C   D            5 intermediate frames (C was held
                                          longer, so it stays a held frame)

The plan is then rendered as a short clip and stretched back to the original
length, with the in-between frames generated by optical flow. Drawings that
were held much longer than the base pattern are deliberate holds, so they keep
their proportional length and never get smoothed into motion.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass, field
from typing import List, Sequence


@dataclass
class Hold:
    """One drawing, and how many source frames it occupies."""

    index: int   # source frame index where the drawing first appears
    length: int  # number of source frames it is held for

    @property
    def end(self) -> int:
        """Last source frame index covered by this hold (inclusive)."""
        return self.index + self.length - 1


@dataclass
class DedupePlan:
    """How to rebuild a clip from its unique drawings."""

    source_frames: int
    fps: float
    holds: List[Hold] = field(default_factory=list)
    base_hold: int = 1
    # One source frame index per intermediate frame, in order.
    output_indices: List[int] = field(default_factory=list)

    @property
    def unique_drawings(self) -> int:
        return len(self.holds)

    @property
    def output_frames(self) -> int:
        return len(self.output_indices)

    @property
    def is_noop(self) -> bool:
        """True when there is nothing to gain: every source frame is unique."""
        return self.output_frames >= self.source_frames

    @property
    def stretch(self) -> float:
        """How much the intermediate is stretched to refill the original length."""
        if not self.output_frames:
            return 1.0
        return self.source_frames / float(self.output_frames)

    @property
    def duplicate_frames(self) -> int:
        return max(0, self.source_frames - self.unique_drawings)

    def describe(self) -> str:
        if self.source_frames == 0:
            return "Empty clip."
        if self.is_noop:
            return (
                f"{self.source_frames} frames, all unique. "
                "Nothing to de-duplicate, so smoothing would not change the motion."
            )
        pct = 100.0 * self.duplicate_frames / self.source_frames
        return (
            f"{self.source_frames} frames, {self.unique_drawings} unique drawings "
            f"({self.duplicate_frames} held, {pct:.0f}%). "
            f"Animated on {self.base_hold}s. "
            f"Rebuilding from {self.output_frames} frames at {self.stretch:.2f}x stretch."
        )

    def to_dict(self) -> dict:
        return {
            "source_frames": self.source_frames,
            "fps": self.fps,
            "base_hold": self.base_hold,
            "unique_drawings": self.unique_drawings,
            "duplicate_frames": self.duplicate_frames,
            "output_frames": self.output_frames,
            "stretch": self.stretch,
            "is_noop": self.is_noop,
            "holds": [{"index": h.index, "length": h.length} for h in self.holds],
            "output_indices": self.output_indices,
        }


def flag_new_drawings(scores: Sequence[float], threshold: float) -> List[bool]:
    """Mark which frames introduce a new drawing.

    `scores[i]` is how different frame i is from frame i-1. Frame 0 is always
    a new drawing because there is nothing before it.
    """
    if not scores:
        return []
    flags = [True]
    for score in scores[1:]:
        flags.append(bool(score >= threshold))
    return flags


def holds_from_flags(flags: Sequence[bool]) -> List[Hold]:
    """Collapse per-frame new-drawing flags into runs."""
    holds: List[Hold] = []
    for i, is_new in enumerate(flags):
        if is_new or not holds:
            holds.append(Hold(index=i, length=1))
        else:
            holds[-1].length += 1
    return holds


def detect_base_hold(holds: Sequence[Hold], *, max_pattern: int = 4) -> int:
    """Work out whether the clip is on 1s, 2s, 3s...

    The base is the most common hold length among the ordinary drawings.
    Deliberate long holds (a still, a held pose) are excluded so they cannot
    drag the estimate upwards, and ties resolve to the shorter pattern, which
    de-duplicates less and is therefore the safer guess.
    """
    lengths = [h.length for h in holds if 1 <= h.length <= max_pattern]
    if not lengths:
        return 1
    counts = Counter(lengths)
    best = max(counts.values())
    return min(length for length, count in counts.items() if count == best)


def build_output_indices(holds: Sequence[Hold], base_hold: int) -> List[int]:
    """Choose which source frames make up the intermediate clip.

    Each drawing contributes `round(length / base_hold)` frames, so a drawing
    held for the base pattern appears once, and one held for six times the
    base still occupies six times as much screen time after the stretch. That
    keeps deliberate holds still instead of melting them into motion.
    """
    base = max(1, int(base_hold))
    indices: List[int] = []
    for hold in holds:
        repeats = max(1, int(round(hold.length / float(base))))
        indices.extend([hold.index] * repeats)
    return indices


def plan_from_scores(
    scores: Sequence[float],
    fps: float,
    *,
    threshold: float,
    force_base_hold: int = 0,
) -> DedupePlan:
    """Full analysis: per-frame difference scores in, rebuild plan out."""
    flags = flag_new_drawings(scores, threshold)
    holds = holds_from_flags(flags)
    base = int(force_base_hold) if force_base_hold and force_base_hold > 0 \
        else detect_base_hold(holds)
    return DedupePlan(
        source_frames=len(flags),
        fps=fps,
        holds=holds,
        base_hold=base,
        output_indices=build_output_indices(holds, base),
    )


def output_time_map(plan: DedupePlan) -> List[float]:
    """Where each final frame sits in the intermediate clip, as a float index.

    Final frame `n` of `source_frames` maps to position `n / stretch` in the
    intermediate. The integer part picks the pair of drawings to blend, the
    fraction is how far between them the in-between sits.

    The last drawing has no successor, so the final slot clamps to it and is
    held rather than interpolated. That is the one place where the source's
    original hold survives, and it is unavoidable without inventing motion
    past the end of the clip.
    """
    if plan.output_frames == 0 or plan.source_frames == 0:
        return []
    last = plan.output_frames - 1
    # Rate-based, not endpoint-matched: output frame n sits n/stretch into the
    # intermediate. Matching the endpoints instead would rescale the whole clip
    # slightly and leave no output frame sitting exactly on a real drawing.
    rate = plan.output_frames / float(plan.source_frames)
    return [min(last, n * rate) for n in range(plan.source_frames)]
